version: '3'

services:
  microservice-nodejs-framework:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/usr/src/app/
    ports:
      - "${PORT}:${PORT}"
    command: npm start